name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, demo]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    container: osrf/ros:jazzy-desktop

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'yano_ws/src'

    - name: Set up workspace
      run: |
        mkdir -p yano_ws
        cd yano_ws
        if [ ! -d src ]; then
          ln -s ../yano_ws/src src || true
        fi
        colcon list

    - name: Install dependencies
      shell: bash
      run: |
        cd yano_ws
        source /opt/ros/jazzy/setup.bash
        rosdep install --from-paths src --ignore-src -y \
          --skip-keys "libopencv-dev libopencv-contrib-dev"

    - name: Build workspace
      shell: bash
      run: |
        cd yano_ws
        source /opt/ros/jazzy/setup.bash
        colcon build --symlink-install --event-handlers console_direct+

    - name: Verify plugin
      shell: bash
      run: |
        cd yano_ws
        source install/setup.bash
        rospack plugins --attrib=plugin rqt_gui_cpp | grep my_rqt_plugin
