name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, demo]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    container: osrf/ros:jazzy-desktop

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'yano_ws/src'

    - name: Debug workspace structure
      run: |
        echo "=== Workspace Structure ==="
        pwd
        ls -lR
        echo "=== ROS Packages ==="
        cd yano_ws && colcon list

    - name: Install rosdep
      run: |
        apt-get update && apt-get install -y python3-rosdep
        rosdep init || true
        rosdep update

    - name: Install dependencies
      run: |
        cd yano_ws
        rosdep install --from-paths src --ignore-src -y \
          --skip-keys "libopencv-dev libopencv-contrib-dev"

    - name: Build workspace
      run: |
        cd yano_ws
        . /opt/ros/jazzy/setup.bash  # source → . に変更
        colcon build --symlink-install --event-handlers console_direct+

    - name: Verify RQT plugin
      run: |
        cd yano_ws
        . /opt/ros/jazzy/setup.bash  # source → . に変更
        . install/setup.bash
        echo "=== Plugin Verification ==="
        rospack plugins --attrib=plugin rqt_gui_cpp
        echo "=== Attempting to load plugin ==="
        timeout 15s rqt --force-discover --standalone my_rqt_plugin || true
