name: ROS 2 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        description: 'ROS 2 workspace to build (e.g. main_ws or sandbox)'
        required: false
        default: 'main_ws'

jobs:
  build:
    name: Build ROS 2 Workspace
    runs-on: ubuntu-24.04
    container:
      image: osrf/ros:jazzy-desktop
      options: --workdir /workspace

    env:
      WORKSPACE_DIR: ${{ github.event.inputs.workspace || 'main_ws' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORKSPACE_DIR }}/src

      - name: Setup ROS environment
        run: |
          #!/usr/bin/env bash
          set -e
          source "/opt/ros/$ROS_DISTRO/setup.bash"
          sudo apt-get update -qq
          sudo apt-get install -y python3-colcon-common-extensions
          sudo rosdep init || true
          rosdep update
        shell: bash {0}

      - name: Install dependencies
        run: |
          #!/usr/bin/env bash
          set -e
          source "/opt/ros/$ROS_DISTRO/setup.bash"
          cd "${{ env.WORKSPACE_DIR }}"
          rosdep install --from-paths src --ignore-src -r -y
        shell: bash {0}

      - name: Build workspace
        run: |
          #!/usr/bin/env bash
          set -e
          source "/opt/ros/$ROS_DISTRO/setup.bash"
          cd "${{ env.WORKSPACE_DIR }}"
          colcon build --symlink-install --event-handlers console_direct+
        shell: bash {0}

      # - name: Run tests
      #   if: ${{ always() }}
      #   run: |
      #     #!/usr/bin/env bash
      #     set -e
      #     source "/opt/ros/$ROS_DISTRO/setup.bash"
      #     source "${{ env.WORKSPACE_DIR }}/install/setup.bash"
      #     cd "${{ env.WORKSPACE_DIR }}"
      #     colcon test --event-handlers console_direct+
      #     colcon test-result --verbose
      #   shell: bash {0}
