name: ROS 2 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker for ROS 2 Humble
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build ROS 2 workspace
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          osrf/ros:humble-desktop \
          bash -c "apt update && apt install -y python3-colcon-common-extensions && \
                   source /opt/ros/humble/setup.bash && \
                   colcon build --symlink-install"

    - name: Run tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          osrf/ros:humble-desktop \
          bash -c "source /opt/ros/humble/setup.bash && \
                   colcon test --event-handlers console_direct+ && \
                   colcon test-result --verbose"

    - name: Debug test results path
      if: always()
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          osrf/ros:humble-desktop \
          bash -c "find /workspace -name '*.xml'"

    - name: Upload test results
      if: always()
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          osrf/ros:humble-desktop \
          bash -c "cat /workspace/build/*/Testing/Temporary/*.xml || echo 'No test results found.'"
