name: ROS 2 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build ROS 2 workspace
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          osrf/ros:humble-desktop \
          bash -c "apt update && apt install -y python3-colcon-common-extensions ros-humble-dynamixel-sdk ros-humble-dynamixel-workbench && \
                   source /opt/ros/humble/setup.bash && \
                   colcon build --symlink-install"
