name: ROS 2 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workspace:
        description: 'ROS 2 workspace to build (e.g. main_ws or sandbox)'
        required: false
        default: 'main_ws'

jobs:
  build:
    name: Build ROS 2 Workspace
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rosdep cache on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-rosdep
          sudo rosdep init || true
          rosdep update

      - name: Build ROS 2 workspace inside Docker
        env:
          WORKSPACE_DIR: ${{ github.event.inputs.workspace }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/${WORKSPACE_DIR} \
            osrf/ros:jazzy-desktop \
            bash -c "\
              source /opt/ros/jazzy/setup.bash && \
              rosdep install --from-paths src --ignore-src -r -y && \
              colcon build --symlink-install"

