name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, demo]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    container: osrf/ros:jazzy-desktop

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'yano_ws/src'

    - name: Set up rosdep
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-rosdep
        sudo rosdep init || true  # 既に初期化済みの場合を想定
        rosdep update

    - name: Install dependencies
      shell: bash
      run: |
        cd yano_ws
        source /opt/ros/jazzy/setup.bash
        rosdep install --from-paths src --ignore-src -y \
          --skip-keys "libopencv-dev libopencv-contrib-dev"

    - name: Build workspace
      shell: bash
      run: |
        cd yano_ws
        source /opt/ros/jazzy/setup.bash
        colcon build --symlink-install --event-handlers console_direct+

    # - name: Verify plugin
    #   shell: bash
    #   run: |
    #     cd yano_ws
    #     source install/setup.bash
    #     rospack plugins --attrib=plugin rqt_gui_cpp | grep my_rqt_plugin
